### ISSUE TITLE
sshIdentityPrivKeyPath=

### ISSUE THREAD

**Issue by lupsyn** [palominolabs/gradle-git-clone-task#2]
I have some problems to setting this variable on Windows env to point to C:/Users/username/.ssh

**Comment by marshallpierce** [comment]
Can you be more specific than "some problems"? :)

**Comment by lupsyn** [comment]
Currently, i've to clone a private repository with gradle in order to add it on my android project:
I've added the public key rsa on github infact : 
C:\Program Files (x86)\OpenSSH\bin>ssh  git@github.com
Enter passphrase for key '/cygdrive/c/Users/Marco/.ssh/id_rsa':
Hi lupsyn! You've successfully authenticated, but GitHub does not provide shell
access.
Connection to github.com closed.


The configuration in build.gradle:

task cloneSomeRepo(type: com.palominolabs.gradle.task.git.clone.GitCloneTask) {
    dir = file("$buildDir/sdk")
    uri = 'git@github.com:Username/RepositoryName.git'
    treeish = 'BranchName' // a git hash, or tag name, or branch name

}

Caused by: com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:512)
        at com.jcraft.jsch.Session.connect(Session.java:183)
        at com.jcraft.jsch.Session$connect.call(Unknown Source)
        at com.palominolabs.gradle.task.git.clone.SshAgentSshSessionFactory.getSession(SshAgentSshSessionFactory.groovy:64)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:248)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1111)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:83)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at com.palominolabs.gradle.task.git.clone.GitCloneTask.setUpRepo(GitCloneTask.groovy:82)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        ... 54 more

**Comment by marshallpierce** [comment]
It doesn't look like you're setting `sshIdentityPrivKeyPath` in your task definition.

**Comment by lupsyn** [comment]
Obiuvsly the rsa private key is determinated with this line of code:
 String sshIdentityPrivKeyPath = Paths.get(System.getProperty('user.home'), '.ssh', 'id_rsa').toString()
Btw if i try to set up manual as sshIdentityPrivKeyPath ="C:\Users\Marco\.ssh\id_rsa"  some format error will occur.

**Comment by marshallpierce** [comment]
You still haven't described the actual error.

**Comment by marshallpierce** [comment]
Closing due to inactivity

**Comment by bipintmobile** [comment]
task cloneSomeRepo(type: com.palominolabs.gradle.task.git.clone.GitCloneTask) {
dir = file("$buildDir/sdk")
uri = '[git@github.com](mailto:git@github.com):Username/RepositoryName.git'
treeish = 'BranchName' // a git hash, or tag name, or branch name
**trySshAgent = false**
}
